### ISSUE TITLE
Clarify which type of GPU is available per project in the whitelist.

### ISSUE THREAD

**Issue by ragnaroklow** [gridcoin-community/Gridcoin-Site#130]
At the moment it only species whether GPUs are available for a project or not. Because some projects only accept Nvidia, AMD or Intel GPUs, it would be useful to specify which type.
![gpu](https://user-images.githubusercontent.com/2970779/47132729-64dbd280-d273-11e8-81e0-9fed4e1a1be0.png)

Maybe by including a small logo for each GPU used?

**Comment by grctest** [comment]
We used to do this, the BOINC project listings web reference does show Intel/AMD/Nvidia GPU support, but support for GPU vendors often changes.. if we can compile a list of GPU vendor support for each projects then sure we could do this.

I'm not sure about showing multiple icons because of how crowded the table already is, perhaps it could be in a hover tooltip?

**Comment by springfielddatarecovery** [comment]
Another way to do this is a badge system. So for example under GPU show the NVIDIA and AMD logos and in the corner of the logo there will be smaller icons for Windows, Linux, OS X, etc. I lack the graphic design chops to do this, but I'd be happy to compile the GPU support information. I think it's less important that the whitelist is completely up to date and more important that is gives _some_ information about GPU + Platform support so a user can easily go there and ask "I have platform x and a gpu, which projects should I join". Plus I imagine it's more frequent that a new project adds GPU support (which we haven't yet caught up the list to yet) than that a project removes GPU support.
