### ISSUE TITLE
Add wiki page for MRC

### ISSUE THREAD

**Issue by delta1513** [gridcoin-community/Gridcoin-Site#341]
The following issue thread will contain suggestions for MRC-related questions and answers that will go onto the wiki page on [gridcoin.us](https://gridcoin.us/wiki/)

I'm going to get the ball rolling and suggest some questions:
- What is MRC?
- Why was MRC made?
- Why do mining pools still exist if MRC makes them redundant?
- If I have enough GRC to stake regularly, do I still need to use MRC?
- Do I need a little bit of GRC to claim my research rewards using MRC?
- What happens if I don't ever claim my rewards with MRC?

**Comment by jamescowens** [comment]
A few more...

Are there fees associated with MRC, and if so, how do they work?
Which one of my addresses gets the payment for MRC?
Why did my MRC request seem to disappear without action?
Is there any possibility of someone else intercepting my MRC payment?

**Comment by jamescowens** [comment]
From ZigzagoonBalloon: Is there a command for MRC for RPC?

**Comment by jamescowens** [comment]
What block do MRC payments become possible?
Can I retrieve currently pending awards via MRC when it becomes possible?

**Comment by delta1513** [comment]
I would like some help answering the following questions because I don't have the information to answer them myself:

1. Which address will receive the MRC reward? Can I redirect it?
2. Is there a command for MRC for RPC?
3. What happens if the MRC queue is full?
4. If the queue is full, how do I push up my payment priority and get in the queue?
5. Why did my MRC request seem to disappear without action?

**Comment by iFoggz** [comment]
createmrcrequest is the rpc command. see help createmrcrequest for more information.

I believe that the MRC will go to the beacon address if I remember correctly. I'm sure Jim will correct me if I am wrong.

**Comment by jamescowens** [comment]
Which address will receive the MRC reward? Can I redirect it?

The address of the key used in your wallet to advertise and validate your beacon is used by the staker to pay your MRC request. This address is labeled in the wallet as “Beacon Rain Address…” This is the only address that can be used for MRC payment because it has been validated by the network with the beacon validation process and therefore is the only address that can be trusted as correct by the staker that is staking your MRC payment.

Is there a command for MRC for RPC?

createmrcrequest. [I will edit this with a more complete explanation.]

What happens if the MRC queue is full?

On mainnet each block can accommodate up to 9 MRC payments. These slots are filled from the “memory pool”, which are submitted transactions. In the case of MRC, this forms a queue with nine slots for MRCs to be placed in the next block by the next staker. Gridcoin generates about 900 blocks a day, so this means the network can accommodate 8100 MRC payments per day. We expect this to be more than enough capacity for the foreseeable future. However it is possible that due to the random nature of demand that all slots could be filled at the time you want to submit your MRC. In that case, you can boost the fee you are paying to move your MRC request up in the queue and displace a lower paying requester, or wait a little bit for the queue to empty and give you an opportunity to submit without boosting the fee. The queue is emptied at each staked block. Any MRCs waiting in the queue that have not been fulfilled when a block is staked become stale and are removed and their transaction fees refunded to the requesters.

If the queue is full, how do I push up my payment priority and get in the queue?

You can make use of the fee boost field on the MRC screen to boost your fee until the screen shows that you can successfully submit. The fee paid by the “tail” of the queue, or the current lowest fee queue entry is available on screen to allow you to easily figure out how much to boost your fee to be able to submit.

Why did my MRC request seem to disappear without action?

There are several reasons why this might occur. If you submitted your MRC right before the staker actually stakes the next block, in which case there may not have been enough time for your request to get to the staker before the block is staked. In that case your MRC will become “stale” and will be removed at the next block and your MRC transaction fee refunded. You can then try to submit another MRC.

If your MRC was near the bottom of the MRC queue and others were trying to submit by boosting fees, it is possible your request could be pushed down beyond the pay limit, which is nine MRCs per block. In that case your MRC request will become stale when the next block is staked. Your MRC will be removed at the next block and your MRC transaction fee refunded. You can then try to submit another MRC.

**Comment by delta1513** [comment]
Closing from merge
